### ISSUE TITLE
Investigating tinycudann MLP layer

### ISSUE THREAD

**Issue by SeanNaren** [SeanNaren/SmallScience#8]
Ben suggested checking out the MLP layer in https://github.com/NVlabs/tiny-cuda-nn as it's a fused version of a typical MLP.

I created a script to benchmark this based on just the MLP: https://github.com/SeanNaren/SmallScience/blob/feat/profiling/tiny.py

I ran the script on an A100 machine using PyTorch 1.11 and CUDA 11.3.

It seems for very small dimensions that the tinycudann MLP works well, however after a certain point it loses compared to our typical nn.Linear:

With autocast enabled (log scale):

<img width="500" alt="Screenshot 2022-04-08 at 22 26 29" src="https://user-images.githubusercontent.com/6707363/163401101-38a0c368-beb7-45a7-b062-1f3359607b3f.png">
<img width="500" alt="Screenshot 2022-04-08 at 22 26 29" src="https://user-images.githubusercontent.com/6707363/163401114-84258935-0d8f-417d-8003-de298b2017f2.png">

Without autocast enabled (log scale):

<img width="500" alt="Screenshot 2022-04-08 at 22 26 29" src="https://user-images.githubusercontent.com/6707363/163401377-f8af5e03-c303-4f7d-91fc-37a79a82a940.png">

<img width="500" alt="Screenshot 2022-04-08 at 22 26 29" src="https://user-images.githubusercontent.com/6707363/163401384-2b4a60e1-a378-42e0-94e7-89cb1e27baa3.png">

**Comment by SeanNaren** [comment]
Would be awesome to get @Tom94 opinion if hes' around :D

**Comment by Tom94** [comment]
Hi there, these results look pretty much as expected, given the setup.

To benefit from fully fused MLPs, you need to
1. Use `FullyFusedMLP` rather than `CutlassMLP` (the latter not being fused at all). AFAIK, PyTorch uses CUTLASS' GEMM routines under the hood as well, which likely explains the very similar performance numbers.
2. Use MLP widths on the order of 16-128 neurons wide. The underlying algorithm for full MLP fusion only works with __tiny__ networks (see section 4 of [this paper](https://tom94.net/data/publications/mueller21realtime/mueller21realtime.pdf)). If the goal is to run MLPs on the order of thousands of neurons wide, I would not recommend using this framework.
3. Use the CUDA/C++ API. Interstingly (and I didn't yet dig deep enough to have a good explanation), going through the PyTorch bindings introduces a roughly ~2x overhead in use-cases that match points (1) and (2), such as the bundled example code for learning an image. This overhead is likely negligible for the kind of MLPs used in your benchmark, though, so no qualms with the Python API there.

Cheers!

**Comment by SeanNaren** [comment]
All makes sense was really easy to work with the framework, fantastic work @Tom94!

I think the intuition that @blefaudeux was that fusing the MLP inside the transformer blocks would give us a pretty hefty speed up. would you agree here @Tom94? I still think it's worth investigating

**Comment by blefaudeux** [comment]
> All makes sense was really easy to work with the framework, fantastic work @Tom94!
> 
> I think the intuition that @blefaudeux was that fusing the MLP inside the transformer blocks would give us a pretty hefty speed up. would you agree here @Tom94? I still think it's worth investigating

I was not sure about what tinyNN was capable of handling, basically "fusing the MLP" is easier said than done (I tried some of it myself with triton, definitely a mouthful even if you can fuse some steps decently :)). As far as I understood I overestimated what size tinyNN was capable of handling, may not be a great fit for you @SeanNaren in the end for the embedding sizes that you're targeting (>> 128) (@Tom94 will obviously know more)

**Comment by SeanNaren** [comment]
was great to try regardless, I learnt something new :)

**Comment by SeanNaren** [comment]
Closing this for now, as I think it's definitive!
